# Generated by Django 4.0 on 2021-12-17 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.AddField(
            model_name='post',
            name='cre_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 9, 5, 28, 388446, tzinfo=utc), verbose_name='Дата публикиции'),
        ),
    ]
